// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm9673tkjMaY_1eX5lJjOx59jncXFnsUw',
    appId: '1:899213709947:web:6c033297ee2c32d81e48de',
    messagingSenderId: '899213709947',
    projectId: 'lostu-f68cb',
    authDomain: 'lostu-f68cb.firebaseapp.com',
    storageBucket: 'lostu-f68cb.firebasestorage.app',
    measurementId: 'G-00YQT43H64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVpop9Mrje0KpECxwCiA7GsXbptdok5WI',
    appId: '1:899213709947:android:337a667f096279041e48de',
    messagingSenderId: '899213709947',
    projectId: 'lostu-f68cb',
    storageBucket: 'lostu-f68cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnJgfRi3Nulm-XOVikhF_HZ5dyaX-QGQY',
    appId: '1:899213709947:ios:d7532dc316ece4dc1e48de',
    messagingSenderId: '899213709947',
    projectId: 'lostu-f68cb',
    storageBucket: 'lostu-f68cb.firebasestorage.app',
    iosBundleId: 'com.example.lostu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnJgfRi3Nulm-XOVikhF_HZ5dyaX-QGQY',
    appId: '1:899213709947:ios:d7532dc316ece4dc1e48de',
    messagingSenderId: '899213709947',
    projectId: 'lostu-f68cb',
    storageBucket: 'lostu-f68cb.firebasestorage.app',
    iosBundleId: 'com.example.lostu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm9673tkjMaY_1eX5lJjOx59jncXFnsUw',
    appId: '1:899213709947:web:52ab183f90f8ca191e48de',
    messagingSenderId: '899213709947',
    projectId: 'lostu-f68cb',
    authDomain: 'lostu-f68cb.firebaseapp.com',
    storageBucket: 'lostu-f68cb.firebasestorage.app',
    measurementId: 'G-XGM7PDHV6L',
  );
}
